sudo: required
services:
    - docker

before_install:
    - docker build -t maximneustroev/docker-react -f Dockerfile.dev .

script:
    - docker run maximneustroev/docker-react npm run test -- --coverage